### ISSUE TITLE
Client closed when placing tank on server (v1.0.1)

### ISSUE THREAD

**Issue by Geko-X** [McJty/DeepResonance#24]
When placing a tank on a server world, the client is forcibly disconnected with a "Disconnected from server" message.

The client is also forcibly disconnected when attempting to rejoin.
The issue does not occur in single player worlds.

Attached are the relevant parts of fml-server-latest.log. The full file can be uploaded if required. No crash log is generated on either the server or client. Note that no relevant information can be found in fml-client-latest.log (but can still be uploaded if required).

Server: http://pastebin.com/uRWHv6YC

**Comment by Elec332** [comment]
It would indeed help if you gave us the fml-latest-client.log, and any other logs you may have (Server one?)

**Comment by Geko-X** [comment]
Client (server join is at about line 10700): https://drive.google.com/file/d/0ByZcdaQLOhubenNCSVVEX09rb1E/view?usp=sharing

Server (client joins at about line 10600): https://drive.google.com/file/d/0ByZcdaQLOhubVkpDandfM3RfQVk/view?usp=sharing

**Comment by smbarbour** [comment]
A user on my server is also having this same issue.  I've instructed him to supply his client log.  Here is the fml-server-latest.log from the server:  https://gist.github.com/acd9650e52bccb710209

Also of note, this line https://github.com/Elecs-Mods/ElecCore/blob/20e9621bd33b9cf6a9533fba80d52b81c2fc3a4f/src/main/java/elec332/core/grid/basic/AbstractWorldGridHolder.java#L172 is causing log spamming which started the moment he placed the tank down in the world.

**Comment by 4rz0** [comment]
The matching client log is here: 
https://dl.dropboxusercontent.com/u/13531495/Minecraft/error/fml-client-latest.log

**Comment by McJty** [comment]
It is possible that I fixed the bug but it has to be tested. You can get a dev version from https://drone.io/github.com/McJty/DeepResonance because I can't test on a server atm

**Comment by Geko-X** [comment]
(Not creating a new issue because this is still related)

I've tested both build 207 and 1.1.0beta1. Both are causing the same crash on server startup.

Crash logs
 - 207: http://pastebin.com/K0GqXmqM
 - 1.1.0b1: http://pastebin.com/dpw7MhAB

**Comment by mrdeadlocked** [comment]
Same issue on smp. :-(

**Comment by McJty** [comment]
Latest build (208) should fix this hopefully

**Comment by Geko-X** [comment]
This fixes the server startup crash, but does not fix the client disconnecting when placing a tank. The same error is generated as before.

**Comment by McJty** [comment]
Geko-X, did you upgrade to the latest ElecCore (released yesterday)?

**Comment by Geko-X** [comment]
Yep. Same error

**Comment by McJty** [comment]
Can you give me the exact stacktrace? I'm a bit lost with all the reports above so a fresh trace with latest of all should help

**Comment by Geko-X** [comment]
No crash logs are generated, so here's some fresh fml-latest logs.

Full fml-server-latest.log. Client joins at about line 10630. https://drive.google.com/file/d/0ByZcdaQLOhubYTd3UFJqOUpLUWc/view?usp=sharing

Snippet of fml-server-latest.log: http://pastebin.com/sBPaLECW

Full fml-client-latest.log. Client joins at about line 10730.
https://drive.google.com/file/d/0ByZcdaQLOhubczVDSTZYWllRVmc/view?usp=sharing

**Comment by McJty** [comment]
I'm baffled. I can't find what could be causing this...

**Comment by Geko-X** [comment]
Good news!

After investigating a hunch that it was a WAILA thing causing the disconnect, I've found that this is in fact the case.

I disabled WAILA on the server and client got the following results. A "success" is able to join without the client being disconnected.

| WAILA on Server | WAILA on Client | Success? |
|:---------------:|:---------------:|:--------:|
|       Yes       |       Yes       |    No    |
|       Yes       |        No       |    Yes   |
|        No       |       Yes       |    No    |
|        No       |        No       |    Yes   |

I used
 - WAILA 1.5
 - DeepResonance build 213
 - ElecCore 1.4.175
 - mcjtylib 1.7.10 (Oct 27 build)

Hope this helps!

**Comment by McJty** [comment]
I just rewrote how the WAILA handling of the tank is done. Can someone test build 214 of Deep Resonance and see if that fixes things?

**Comment by Geko-X** [comment]
Just tested, and all fixed!

**Comment by McJty** [comment]
FINALLY! :-)

**Comment by Elec332** [comment]
NOW it's fixed :)
